version: '3'

services:
  modohayaku:
    container_name: modohayaku
    build: ./
    volumes:
      - ./share:/home/modohayaku:ro
      - ./xinetd:/etc/xinetd.d/modohayaku:ro
    ports:
      - "10002:10101"
    expose:
      - "10101"
    restart: always
