version: '3'

services:
  modomodohayaku:
    container_name: modomodohayaku
    build: ./
    volumes:
      - ./share:/home/modomodohayaku:ro
      - ./xinetd:/etc/xinetd.d/modomodohayaku:ro
    ports:
      - "10006:10101"
    expose:
      - "10101"
    restart: always
